#!/bin/bash
#
# skripti algus
for (( arv=1; arv<11; arv++ ))
do
jaak=$(($arv % 2))
if [ $jaak -eq 0 ]; then
summa=$(($summa + arv))
echo $summa
fi
done
echo "paarisarvude summa on $summa"
#
# skripti lopp
