#!/bin/bash
#
# skripti algus
echo -n "Sisesta külg a: " #küsib et inimene sisestaks külje a
read a # jätab meelde külje a
echo -n "Sisesta külg b: " # küsib et inimene sisestaks külje b
read b #loeb külg b
#väljastused + arvutused
a2=`echo "scale=2;$a^2" | bc`
b2=`echo "scale=2;$b^2" | bc`
c2=`echo "scale=2;$a2+$b2" | bc`
c=`echo "scale=2;sqrt($c2)" | bc`
echo "c= " $c
#
# skripti lõpp
