#!/bin/bash
#
# skripti algus
echo -n "Sisestage ridade arvu: " #Küsib ridade arvu
	read ridade_arv #jätab arvu meelde
echo -n "Sisestage tärnide arv reas: " #küsib tärnide arvu
	read tarnid #jätab arvu meelde
for (( i = 1; i <= $ridade_arv; i++ )) # see on loopi pikkus
	do
		echo -n "$i. " #kirjutab siia reanumbri
if [ "$i" == 1 ] || [ "$i" == $ridade_arv ] #kui
	then #siis
	for (( j = 1; j <= $tarnid; j++ )) #see on loopi laius
		do
			echo -n "*" #tärn mis kirjutatakse reale
		done
	else
		echo -n "*" #tärn real
	for (( a = 2; a < $tarnid; a++ )) #teeb selle kujundi
		do
			echo -n " " #tühik mis keskele tuleb
		done
	echo -n "*" #tärn real
fi
echo "" #tühi rea lõpp
done
#
# skripti lõpp
